### ISSUE TITLE
Math does not render properly

### ISSUE THREAD

**Issue by Minoo7** [mlcivilengineer/obsankipy#1]
When running

```python ./src/obsankipy.py ./examples/vault/.obsankipy/config.yaml```

And viewing the cards in Anki, everything looks good except the math formulas.

![image](https://github.com/mlcivilengineer/obsankipy/assets/40737862/658b0db2-6fab-466e-a00e-7b639aeed866)

I installed Latex on my system using MiKTeX

**Comment by mlcivilengineer** [comment]
Assuming you are on windows, did you go to Settings in MikTeX’s maintenance window, and make sure "Install missing packages on the fly" is set to "Always", not to "Ask me first"? The Anki documentation states that that is needed https://docs.ankiweb.net/math.html and that may be the issue. 

I haven't tested much the program on windows systems, I mainly run Linux but try changing this setting and it may suffice

**Comment by Minoo7** [comment]
Using \[ \] instead of $$ and \( \) instead of $, is what only seemed to work for me. [And apparently it's the recommended way to go](https://tex.stackexchange.com/questions/503/why-is-preferable-to)

I created a pull request that fixed my issues: #2

**Comment by mlcivilengineer** [comment]
Sorry for taking so long to see this. I just commited the changes you suggested to the $$ but not through your PR because there were other changes besides this one which I can't identify and understand. Please create a new PR if you think those changes should also go to the main branch.
